# Generated by Django 4.2 on 2023-05-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avatar/avatar-11.jpg', null=True, upload_to='img/photos/%Y/%m/%d/'),
        ),
    ]
