# Generated by Django 4.2 on 2023-05-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='interior',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='is_featured',
            field=models.BooleanField(max_length=120),
        ),
        migrations.AlterField(
            model_name='cars',
            name='miles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='passengers',
            field=models.IntegerField(),
        ),
    ]
