# Generated by Django 4.2 on 2023-05-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_car_price_alter_cars_interior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cars',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cars',
            name='fuel_type',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='cars',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
